version: '2'
services:
    comdatagaricapp-app:
        image: comdatagaricapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://comdatagaricapp-mysql:3306/comdatagaricapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    comdatagaricapp-mysql:
        extends:
            file: mysql.yml
            service: comdatagaricapp-mysql
